name: Salesforce Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Check Salesforce CLI Version
        run: sfdx --version

      - name: Deploy to Salesforce
        run: sfdx force:source:deploy -p force-app

      - name: Success Message
        run: echo "Salesforce CI Pipeline Working"
