name: Salesforce CI pipeline
on: 
  push: 
    branches: 
    - dev
  pull_request: 
     branches: 
       - dev

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repository
          uses: actions/checkout@v3
          -name: Install Node
           uses: actions/setup-node@v3
           with:
             node-version: '18'

           -name: Install Salesforce CLI
             run: npm install -g
@salesforce/cli
           -name: Dispaly Salesforce CLI version
             run: sf --version

             -name: Run Apex Tests
               run: sf apex run test
--synchronous               
           








             
             
        
