name: Salesforce CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version

      - name: Authenticate Dev Hub
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias DevHub --set-default

      - name: Create Scratch Org
        run: |
          sf org create scratch \
          --definition-file config/project-scratch-def.json \
          --alias CIOrg \
          --duration-days 1 \
          --set-default

      - name: Deploy Source
        run: |
          sf project deploy start --source-dir force-app

      - name: Run Apex Tests
        run: |
          sf apex run test --result-format human --code-coverage --wait 20

      - name: Delete Scratch Org
        if: always()
        run: |
          sf org delete scratch --target-org CIOrg --no-prompt